$font = Monospace

general {
    hide_cursor = false
}

animations {
    enabled = true
    bezier = linear, 1, 1, 0, 0
    animation = fadeIn, 1, 5, linear
    animation = fadeOut, 1, 5, linear
    animation = inputFieldDots, 1, 2, linear
}

background {
    path = $HOME/wallpapers/wallpapers/autumn_forest.png
    blur_size = 3
    blur_passes = 5
    brightness = 0.72
    contrast = 0.8
}


input-field {
    monitor =
    size = 8%, 3%
    outline_thickness = 1
    inner_color = rgb(15, 15, 15)

    font_color = rgb(240, 240, 240)
    fade_on_empty = false
    rounding = 15

    font_family = $font
    placeholder_text =  <i><span foreground="##cdd6f4">Input Password...</span></i>
    dots_text_format = *
    dots_size = 0.32
    dots_spacing = 0.3

    position = 0, 60
    valign = bottom
}

# TIME
label {
    monitor =
    text = cmd[] date +"%H"
    font_size = 175
    font_family = JetBrains Mono Extrabold
    position = -50, 143
    color = rgb(144, 213, 174)
}

# TIME
label {
    monitor =
    text = cmd[] date +"%M"
    font_size = 175
    font_family = JetBrains Mono Nerd Font Mono ExtraBold
    position = 50, -83
}
